require("colorbuddy").setup()

Color.new('white',     '#ffffff')
Color.new('red',       '#ff385d')
Color.new('pink',      '#bc7bc9')
Color.new('green',     '#99ff99')
Color.new('yellow',    '#89c3f5')
Color.new('blue',      '#bda348')
Color.new('aqua',      '#8ec07c')
Color.new('cyan',      '#8abeb7')
Color.new('purple',    '#8e6fbd')
Color.new('violet',    '#e6d357')
--Color.new('orange',    '#bb80ff')
Color.new('orange',    '#a6d2e0')
Color.new('brown',     '#7dc47c')
Color.new('seagreen',  '#698b69')
Color.new('turquoise', '#698b69')
